const schema = {
  type: "object",
  properties: {
    first_name: {
      type: "string",
      minLength: 1,
      pattern: "^(?!\\s*$).+",
    },
    last_name: { type: "string", pattern: "^(?!\\s*$).+" },
    username: { type: "string", minLength: 3, pattern: "^(?!\\s*$).+" },
    email: { type: "string", format: "email", minLength: 5 },
    password: { type: "string", minLength: 5, maxLength: 20, pattern: "^(?!\\s*$).+" },
    mobile: {
      type: "string",
      pattern: "^([0|+[0-9]{1,5})?([7-9][0-9]{9})$",
    },
    address: { type: "string", minLength: 5, pattern: "^(?!\\s*$).+" },
    country: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    gst_legal_entity_name: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    gst_business_address: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    gst_city_code: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    gst_no: { type: "string", minLength: 8, pattern: "^(?!\\s*$).+" },
    name_as_per_pan: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    pan_no: {
      type: "string",
      pattern: "^[A-Z]{5}\\d{4}[A-Z]$",
    },
    pan_date_of_incorporation: { type: "string", format: "date" },
    subscriber_id: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    subscriber_type: { type: "string", enum: ["BPP", "BAP", "BG"] },
  },
  errorMessage: {
    properties: {
      first_name: "first_name should be valid, current value is ${/first_name}",
      last_name: "last_name should be valid, current value is ${/last_name}",
      username: "username should be valid, current value is ${/username}",
      email: "email should be valid, current value is ${/email}",
      password: "password should be valid, current value is ${/password}",
      mobile: "mobile should be valid, current value is ${/mobile}",
      address: "address should be valid, current value is ${/address}",
      country: "country should be valid, current value is ${/country}",
      gst_legal_entity_name: "gst_legal_entity_name should be valid, current value is ${/gst_legal_entity_name}",
      gst_business_address: "gst_business_address should be valid, current value is ${/gst_business_address}",
      gst_city_code: "gst_city_code should be valid, current value is ${/gst_city_code}",
      gst_no: "gst_no should be valid, current value is ${/gst_no}",
      name_as_per_pan: "name_as_per_pan should be valid, current value is ${/name_as_per_pan}",
      pan_no: "pan_no should be valid, current value is ${/pan_no}",
      pan_date_of_incorporation:
        "pan_date_of_incorporation should be valid, current value is ${/pan_date_of_incorporation}",
      subscriber_id: "subscriber_id should be valid, current value is ${/subscriber_id}",
      subscriber_type: "subscriber_type should be valid i.e. from (BPP, BAP, BG), current value is ${/subscriber_type}",
    },
  },
  required: [
    "first_name",
    "username",
    "email",
    "password",
    "mobile",
    "address",
    "country",
    "gst_legal_entity_name",
    "gst_business_address",
    "gst_city_code",
    "gst_no",
    "name_as_per_pan",
    "pan_no",
    "pan_date_of_incorporation",
    "subscriber_id",
    "subscriber_type",
  ],
}

export default schema
